# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59347b5af3f478186c81dd42053bf76474386ed094280044a5f9b66fbbd88c0d89f004644bcea7afb56c5826bf085df91cadc2652981737db0439db2222b7935

test:
  secret_key_base: 6396cb22cafc75c1c96c7ba3f74e46e79b3fa40867e4c333d351629a392c68dacf2227df7e74aa7b1eb38402df1ce6dc0428d51a3706d005e1336f5b6e964a90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
